# This is a basic workflow to help you get started with Actions

name: k8s-arm64-sync

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0,10,20,30,40,50 * * * *'
    
jobs:
  armv7_job:
    # The host should always be Linux
    runs-on: ubuntu-18.04
    name: Build on ubuntu-18.04 armv7
    steps:
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu18.04
          install: |
              case "${{ matrix.distro }}" in
                ubuntu*|jessie|stretch|buster|bullseye)
                  apt-get update -q -y
                  apt-get install -q -y git curl
                  ;;
                fedora*)
                  dnf -y update
                  dnf -y install git which curl
                  ;;
                alpine*)
                  apk update
                  apk add git curl
                  ;;
              esac

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            uname -a
            curl -O -L https://storage.googleapis.com/kubernetes-release/release/$(curl -sSL https://dl.k8s.io/release/stable.txt)/bin/linux/arm64/kubeadm
            chmod +x kubeadm
      - name: Get the output
        # Echo the `uname` output parameter from the `runcmd` step
        run: |
          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
