# This is a basic workflow to help you get started with Actions

name: CI

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,17 * * *'

jobs:
  armv7_job:
    # The host should always be Linux
    runs-on: ubuntu-18.04
    name: Build on ubuntu-18.04 aarch64
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu18.04

      - name: Get the output
        run: |
            KUBERNETES_RELEASE_VERSION="$(curl -sSL https://dl.k8s.io/release/stable.txt)"
            KUBERNETES_VERSION=${INPUT_KUBERNETES_VERSION:=${KUBERNETES_RELEASE_VERSION}}
            echo "currect version ${KUBERNETES_VERSION}"
            curl -O -L https://storage.googleapis.com/kubernetes-release/release/${KUBERNETES_VERSION}/bin/linux/arm64/kubeadm
            chmod +x kubeadm
            images=$(./kubeadm config images list --kubernetes-version=${KUBERNETES_VERSION})

            echo "image list: ${images}"

            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin chaunceyjiang

            while IFS='/' read key value; do
                image=${key}/${value}
                docker pull ${image}
                if [[ "${value}" == "coredns/coredns"* ]]; then
                    value=${value/coredns\//""}
                fi

                new_image=chaunceyjiang/${value}

                docker tag ${image} ${new_image}
                docker push ${new_image}
            done <<< ${images}
